app/config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('pension/', include('food.urls')),
    path('', views.index, name='post_list'),

]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/food/urls.py
from django.urls import path
from food import views


app_name = 'food'

urlpatterns = [
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:pk>/', views.post_detail, name='post_detail'),
]

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

app/templates/posts/post_detail.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

    <h1>팬션 디테일 페이지</h1>
        <img src="{{ pension.photo }}" alt="">
        <p>{{pension.name}}</p>
        <p>{{pension.price}}</p>
        <p>{{pension.address}}</p>
        <p>{{pension.check_in}}</p>
        <p>{{pension.check_out}}</p>

        <p>{{pension.info}}</p>
        <p>{{pension.theme}}</p>


{% endblock %}

app/templates/posts/post_list.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

    <h4>pension list</h4>
<div>
    {% if user.is_authenticated %}

         <form action="{% url 'members:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm" style="margin-bottom: 10px">
                로그아웃하기
            </button>
        </form>

    {% else %}
    <a href="{% url 'members:login' %}" class="btn btn-primary btn-sm" style="margin-bottom: 10px">Sign in</a>
    <a href="{% url 'members:signup' %}" class="btn btn-info btn-sm" style="margin-bottom: 10px">Sign up</a>
    {% endif %}
</div>

<div class="container">
    <div class="row">
        {% for pension in pensions %}
        <div class="col-4 mb-3">
            <div class="card">
                <a href="{% url 'food:post_detail' pk=pension.pk %}"><div class="card-img-top" style="height: 200px; background-image: url('{{pension.photo}}'); background-size: cover;"></div></a>
                <div class="card-body">
                    <h5 class="card-title">{{pension.name}}</h5>
                    <p class="card-text">{{pension.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}