app/config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('pension/', include('food.urls')),
    path('', views.index, name='post_list'),

]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/food/urls.py
from django.urls import path
from food import views


app_name = 'food'

urlpatterns = [
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:pk>/', views.post_detail, name='post_detail'),
]

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body class="container" style="text-align: center">

        <h3><a href="{% url 'food:post_list' %}">야놀자 팬션</a></h3>
    {% if user.is_authenticated %}
        <h5>{{ user }}님 환영합니다.</h5>
    {% endif %}

    <!--user가 인증되어있으면 '로그아웃하기' 라는 링크를 보여주고 아니면 '로그인하기' 링크 보여주기 -->


    <!--logout_view를 구현-->
    <!--request.method가 POST일 경우,-->
    <!--request.user를 로그아웃시킴-->

    <!--URL: /members/logout/-->
    <!--view: members.views.logout_view-->
    <!--로그아웃 완료 후에는 index 로 redirect-->
        {% block content %}
        {% endblock %}
</body>
</html>